[package]
name = "coupledcats"
version = "0.1.0"
edition = "2021"


[dependencies]
display-info = "0.5.1"


# grpc
tonic = "0.12"
prost = "0.13"
tokio = { version = "1.0", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
] }
tokio-stream = "0.1"
async-stream = "0.2"

serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"

# logging
log = "0.4"
fern = { version = "0.6", features = ["colored"] }

color-eyre = "0.6"
humantime = "2.1.0"
rand = "0.8.5"
bevior_tree = "0.7.0"
bevy = "0.15.0"

[build-dependencies]
tonic-build = "0.12"
